TEMPLATE_ROOT = /
#######默认配置
NATIVE_CALL = TRUE
COMPILE_CLASS=FALSE
DIRECT_BYTE_OUTPUT = TRUE
TEMPLATE_CHARSET = UTF-8
MVC_STRICT=FALSE

#内部使用
DEBUG=TRUE
#######默认配置结束







#######编译成class的选项
COMPILE_CLASS_KEEP_SOURCE=TRUE
#OPTIMIZE_COMPILE_LATTER=FALSE
#OPTIMIZE_COMPILE_WORKER_NUM=2
#######\u7F16\u8BD1\u6210class\u7684\u5176\u4ED6\u9009\u9879\u7ED3\u675F